import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/navigation/navigation";

import { SignInProvider, SignIn } from "@/components/sign-in/signin";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col lg:flex-row">
        {/* <SignInProvider> */}
        <SignIn>
          <Navigation />
          <div className="h-full w-full lg:basis-[calc(100%-200px)]">
            {children}
          </div>
        </SignIn>
        {/* </SignInProvider> */}
      </body>
    </html>
  );
}
