import "./globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/navigation/navigation";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import { SignIn } from "@/components/sign-in/signin";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans flex flex-col lg:flex-row">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <SignIn>
            <Navigation />
            {children}
          </SignIn>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
